
{% set version = "2.0.0b1" %}

package:
  name: terrainbento
  version: {{ version }}

source:
  url: https://github.com/TerrainBento/terrainbento/archive/v{{ version }}.tar.gz
  sha256: 73dbdd6721decf3b902b860fffd640502a58582a8d815b1878a82680dc5b2d6e


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - xarray
    - dask
    - holoviews
    - pandas
    - jupyter
    - landlab >=2.0.0b5 <2

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-runner

  imports:
    - terrainbento

  commands:
      - pytest --pyargs terrainbento tests --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"
  source_files:
      - tests/data/*

about:
  home: https://terrainbento.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Multi-model package for earth surface processes'
  description: |
    A modular landscape evolution modeling package for mulit-model analysis built on top of the Landlab Toolkit.
  doc_url: https://terrainbento.readthedocs.io/
  dev_url: https://github.com/TerrainBento/terrainbento

extra:
  recipe-maintainers:
    - kbarnhart
