travis:
  secure:
    BINSTAR_TOKEN: WuPLkEUThQLlQP9C8vndQSbHnm6njhWTWAhzHLUdrlx2LVnHlXmdMsFRUiQBsMEhjA3s4WH/K7UK3X9IkjUt+tYfI5irktRSwThY/e7cHp4d3hbDCMHxe2iRVsT3W0RFlDqHjEknLh2GSmC9Ui0DJ291+wOELIPJmKCJZvabEYrQI1DDL/hz4zn+zKLQ5oBw6PekCsDbqPNYGEzettfrZhmo42TIdGO/wdE84eG9rS5XhFQVQRpfhvdLNP7PuQfPc4ECt0rZv7nR6Cv4uLdTC6gfraZSMSGqWZaAvujFsApESAw4KLNueMgDT81MG2zM8rBifjUBCBB02faOQgd+vQosHZ7dZoUxZQe+WtJ1melfuM0ZcTwNaUZYfV8nhzWJT0CT35AhP3rny7FfnhePG8E1XdMiofHW+r2pTbZnpJ146ccdjEYhFTbXsWLt5qOHf5jt+sENiXfQKZuje3F1OrtrCOPfDJdVpxd8r9AYy+rPGB98gnuObFZub/E5OHsKMRgW5qxd2IZPL75p1cLRlg8TkF3gFJwwfdQxD1qQgg0GK12Aq3dffEhH6iioRutTK+J3gk/AJK5NsF92TgUJ16IkajFnCVSbXZRL65kxo9HFykYcRybgN5prM2vXmoXBIZt3R4Rqdr70kMkgHzXdDZXR3S3oklIxcIPSpFKfABA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
